server:
  port: "8080"
  host: "localhost"

database:
  host: "localhost"
  port: "3306"
  name: "task_manager"
  user: "root"
  password: "root"

jwt:
  access_secret: "your-super-secret-access-key-change-in-production"
  refresh_secret: "your-super-secret-refresh-key-change-in-production"
  access_expire: "30m"
  refresh_expire: "168h"

oauth:
  google:
    client_id: "686501927377-thrds9to0u1piic3ejnteeq01ss2i329.apps.googleusercontent.com"
    client_secret: "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"
    redirect_url: "https://showcase-project.my.id/api/v1/auth/oauth/google/callback"

cors:
  allowed_origins:
    - "http://localhost:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
    - "Accept"
    - "Origin"
  allow_credentials: true
  max_age: 86400