# config.yaml example
server:
  port:
  host:

database:
  host:
  port:
  name:
  user:
  password:

jwt:
  access_secret:
  refresh_secret:
  access_expire:
  refresh_expire:

oauth:
  google:
    client_id:
    client_secret:
    redirect_url:
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://localhost:8080"
    - "https://yourdomain.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  allow_credentials: true
  max_age: 86400