name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_PORT }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          echo "🚀 Starting deployment..."

          # Check if deployment script exists
          if [ ! -f "/opt/scripts/deploy-task-management-golang.sh" ]; then
            echo "❌ Deployment script not found at /opt/scripts/deploy-task-management-golang.sh"
            exit 1
          fi

          # Make script executable and run it
          sudo chmod +x /opt/scripts/deploy-task-management-golang.sh
          sudo /opt/scripts/deploy-task-management-golang.sh

          echo "✅ Deployment completed!"